### ISSUE TITLE
SmsCodeAuthenticationFilter

### ISSUE THREAD

**Issue by waterCoding** [chougui123/RuoYi-Vue-SmsLogin#1]
SmsCodeAuthenticationFilter是不是多余的，我看都没有用到，我删除之后还是正常运行的

**Comment by chougui123** [comment]
这个不是多余的，你看clean后重新install再试试



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月22日(星期一) 下午4:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [chougui123/RuoYi-Vue-SmsLogin] SmsCodeAuthenticationFilter (Issue #1)





 
SmsCodeAuthenticationFilter是不是多余的，我看都没有用到，我删除之后还是正常运行的
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by waterCoding** [comment]
我看那个类上面是灰的，我用账户密码方式登录的时候在UsernamePasswordAuthenticationFilter的attemptAuthentication方法打了断点好像也没进去，我clean和install之后还是可以

**Comment by chougui123** [comment]
这个过滤器主要是过滤短信登录，你删了他就拦截不到了
